### ISSUE TITLE
No tags Issue

### ISSUE THREAD

**Issue by Ankuraxz** [Ankuraxz/Tagonizer-2#37]
In case Tags of a particular type isn't present, remove that tag from the frontend.

**Comment by vnikonov63** [comment]
Hello! I will definitely look into that tomorrow!

**Comment by vnikonov63** [comment]
Bug fixed. Now if the tag doesn't exists, it is not displayed. The rest of the code is working good
![Screen Shot 2021-03-08 at 11 49 27 PM](https://user-images.githubusercontent.com/62755968/110373551-0d6b7680-8069-11eb-87d6-0c4931b39e0b.png)
![Screen Shot 2021-03-08 at 11 49 34 PM](https://user-images.githubusercontent.com/62755968/110373583-13615780-8069-11eb-9cd7-b79e73330e82.png)

**Comment by Ankuraxz** [comment]
@merrcury  Please create a latest review
